version: "3.8"

services:

    webserver:
        build:
            context: ./docker/bin/${PHPVERSION}
        container_name: "${PROJECT_NAME}"
        restart: "always"
        ports:
            - "${LOCAL_HTTP_PORT}:80"
            - "${LOCAL_HTTPS_PORT}:443"
        volumes:
            - ${DOCUMENT_ROOT}:/var/www/html:rw
            - ${PHP_INI}:/usr/local/etc/php/php.ini
            - ${SSL_DIR}:/etc/apache2/ssl/
            - ${VHOSTS_DIR}:/etc/apache2/sites-enabled
            - ${APACHE_LOG_DIR}:/var/log/apache2
            - ${XDEBUG_LOG_DIR}:/var/log/xdebug
        environment:
            APACHE_DOCUMENT_ROOT: ${APACHE_DOCUMENT_ROOT}
            XDEBUG_CONFIG: "client_host=host.docker.internal remote_port=${XDEBUG_PORT}"
        extra_hosts:
            - "host.docker.internal:host-gateway"