version: "3.8"

services:

    appserver:
        build:
            context: ./docker/dockerfiles/${PHP_VERSION}
        container_name: "${PROJECT_NAME}"
        restart: "always"
        ports:
            - "${LOCAL_HTTP_PORT}:80"
            # - "${LOCAL_HTTPS_PORT}:443"
        volumes:
            - ${DOCUMENT_ROOT}:/var/www/html:rw
            - ${PHP_INI}:/usr/local/etc/php/php.ini
            - ${DIR_SSL}:/etc/apache2/ssl/
            - ${DIR_VHOSTS}:/etc/apache2/sites-enabled
            - ${DIR_APACHE_LOG}:/var/log/apache2
        environment:
            APACHE_DOCUMENT_ROOT: ${DOCUMENT_ROOT_APACHE}
        extra_hosts:
            - "host.docker.internal:host-gateway"

    # ---------------------------------------------------
    # Uncomment the following if using database image
    # ---------------------------------------------------
    # database:
    #     build:
    #         context: "./docker/dockerfiles/$DB_VERSION}"
    #         container_name: "${PROJECT_NAME}-DB"
    #         restart: "always"
    #         ports:
    #             - "$DB_LOCAL_PORT}:3306"
    #         volumes:
    #             - "$DB_DATA_PATH}:/var/lib/mysql"
    #             - "$DB_LOG_PATH}:/var/log/mysql"
    #         environment:
    #             MYSQL_DATABASE: $DB_DATABASE}
    #             MYSQL_ROOT_PASSWORD: $DB_ROOT_PASSWORD}